#!/usr/bin/env python
import hydra

@hydra.main(config_path="config/plotting", config_name="plotting.yaml")
def run_plotting(cfg : DictConfig) -> None:
    pass



if __name__ == "__main__":
    pass
    #run_plotting()